#!/bin/bash


Active="y"
# Main loop
while [ "$Active" = "y" ]; do
read -p "Enter a passphrase (or 'exit' to quit): " userpass
    if [ "$userpass" = "exit" ]; then
        Active="n"
    else
          if grep -q "$userpass" /home/conoaks/Documents/rockyou.txt; then
              echo "The password '$userpass' is in rockyou.txt."
          else
              echo "The password '$userpass' is not in rockyou.txt."
          fi

            if grep -q "$userpass" /home/conoaks/Documents/rockyou.txt; then
                echo "The password '$userpass' is in rockyou.txt."
            else
                echo "The password '$userpass' is not in rockyou.txt."
            fi
         read -p "Do you want to continue? (y/n): " continue_choice
         if [ "$continue_choice" != "y" ]; then
            Active="n"
         fi
    fi

    if grep -q "$userpass" /home/conoaks/Documents/rockyou.txt; then
        echo "The password '$userpass' is in rockyou.txt."
    else
        echo "The password '$userpass' is not in rockyou.txt."
    fi
done

echo "Goodbye!"
